          
name: build_dotnet

on:
  push:
    branches: [ develop, release/2.2, release/1.8 ]
  pull_request:
    branches: [ develop, release/2.2, release/1.8 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout...
      uses: actions/checkout@v2
    - name: Adding msbuild to PATH...
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restoring NuGet Packages...
      run: nuget restore webapp-net/DxaModules.sln
    - name: Building and Publishing Web App...
      run: msbuild webapp-net/DxaModules.sln /p:Configuration=Release
